# Generated by Django 4.2.23 on 2025-09-23 11:46

import core.models.user
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0031_alter_mutationlog_client_mutation_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interactiveuser",
            name="legacy_id",
        ),
        migrations.AddField(
            model_name="interactiveuser",
            name="date_deactivated",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="interactiveuser",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="interactiveuser",
            name="json_ext",
            field=models.JSONField(blank=True, db_column="Json_ext", null=True),
        ),

        migrations.AddField(
            model_name="interactiveuser",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="exportablequerymodel",
            name="create_date",
            field=models.DateTimeField(
                db_column="DateCreated", default=datetime.datetime.now
            ),
        ),
        migrations.AlterField(
            model_name="exportablequerymodel",
            name="expire_date",
            field=models.DateTimeField(
                db_column="DateExpiring",
                default=core.models.user._get_default_expire_date,
            ),
        ),
        migrations.AlterField(
            model_name="interactiveuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="interactiveuser",
            name="uuid",
            field=models.UUIDField(
                db_column="UUID", default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="interactiveuser",
            name="validity_from",
            field=models.DateTimeField(
                db_column="ValidityFrom", default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="interactiveuser",
            name="validity_to",
            field=models.DateTimeField(
                blank=True, db_column="ValidityTo", default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.", # noqa:  E501
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalInteractiveUser",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, editable=False
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_column="UUID",
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "json_ext",
                    models.JSONField(blank=True, db_column="Json_ext", null=True),
                ),
                ("date_deactivated", models.DateTimeField(default=None, null=True)),

                ("version", models.IntegerField(default=1)),
                (
                    "validity_from",
                    models.DateTimeField(
                        db_column="ValidityFrom",
                        default=datetime.datetime.now,
                        null=True,
                    ),
                ),
                (
                    "validity_to",
                    models.DateTimeField(
                        blank=True, db_column="ValidityTo", default=None, null=True
                    ),
                ),
                ("last_name", models.CharField(db_column="LastName", max_length=100)),
                (
                    "other_names",
                    models.CharField(db_column="OtherNames", max_length=100),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_column="Phone", max_length=50, null=True
                    ),
                ),
                ("login_name", models.CharField(db_column="LoginName", max_length=50)),
                (
                    "last_login",
                    models.DateTimeField(blank=True, db_column="LastLogin", null=True),
                ),
                (
                    "health_facility_id",
                    models.IntegerField(blank=True, db_column="HFID", null=True),
                ),
                ("audit_user_id", models.IntegerField(db_column="AuditUserID")),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="EmailId", max_length=200, null=True
                    ),
                ),
                (
                    "private_key",
                    models.CharField(
                        blank=True,
                        db_column="PrivateKey",
                        help_text="The private key is actually a password salt",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        db_column="StoredPassword",
                        help_text="By default a SHA256 of the private key (salt) and password",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "password_validity",
                    models.DateTimeField(
                        blank=True, db_column="PasswordValidity", null=True
                    ),
                ),
                (
                    "is_associated",
                    models.BooleanField(
                        blank=True,
                        db_column="IsAssociated",
                        help_text="has a claim admin or enrolment officer account",
                        null=True,
                    ),
                ),
                (
                    "role_id",
                    models.IntegerField(blank=True, db_column="RoleID", null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        db_column="LanguageID",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical interactive user",
                "verbose_name_plural": "historical interactive users",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
