# Generated by Django 6.0.6 on 2026-06-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0004_paymentbatch_hospital'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sosyspaymentlog',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='sosyspaymentlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sosyspaymentlog',
            name='claim_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sosyspaymentlog',
            name='gateway_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
